-- Table: public.routes

-- DROP TABLE public.routes;

CREATE TABLE public.ICAO_codes
(
    ICAO_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ICAO_dep character varying(4) COLLATE pg_catalog."default",
    ICAO_arr character varying(4) COLLATE pg_catalog."default",
    CONSTRAINT pk_ICAO_codes PRIMARY KEY (ICAO_id)
)

TABLESPACE pg_default;

ALTER TABLE public.ICAO_codes
    OWNER to postgres;