-- Table: public.infos

-- DROP TABLE public.infos;

CREATE TABLE public.infos
(
    infos_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    infos_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    infos_subscribe character varying(750) COLLATE pg_catalog."default",
	infos_icao character varying(3) COLLATE pg_catalog."default",
	infos_iata character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT pk_infos PRIMARY KEY (infos_id)
)

TABLESPACE pg_default;

ALTER TABLE public.infos
    OWNER to postgres;