-- Table: public.routes

-- DROP TABLE public.routes;

CREATE TABLE public.routes
(
    routes_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    routes_flight character varying(50) COLLATE pg_catalog."default" NOT NULL,
    routes_icao integer,
    routes_iata integer,
    CONSTRAINT pk_routes PRIMARY KEY (routes_id),
	CONSTRAINT routes_routes_icao_fkey FOREIGN KEY (routes_icao)
        REFERENCES public.icao_codes (icao_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	CONSTRAINT routes_routes_iata_fkey FOREIGN KEY (routes_iata)
        REFERENCES public.iata_codes (iata_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.routes
    OWNER to postgres;