-- Table: public.mtm_additions

-- DROP TABLE public.mtm_additions;

CREATE TABLE public.mtm_additions
(
    mtm_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    mtm_route integer,
    mtm_info integer,
    CONSTRAINT pk_mtm PRIMARY KEY (mtm_id),
    CONSTRAINT mtm_additions_mtm_info_fkey FOREIGN KEY (mtm_info)
        REFERENCES public.infos (infos_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT mtm_additions_mtm_route_fkey FOREIGN KEY (mtm_route)
        REFERENCES public.routes (routes_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.mtm_additions
    OWNER to postgres;