-- Table: public.models

-- DROP TABLE public.models;

CREATE TABLE public.models
(
    models_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    models_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    models_dev_country character varying(150) COLLATE pg_catalog."default",
    models_scheme_model character varying(150) COLLATE pg_catalog."default",
    models_engines_number integer NOT NULL,
    models_engines_name character varying(150) COLLATE pg_catalog."default",
    models_size integer,
    models_loadout numeric(7,2),
    models_pass numeric(7,2),
    CONSTRAINT models_pkey PRIMARY KEY (models_id),
    CONSTRAINT models_models_size_fkey FOREIGN KEY (models_size)
        REFERENCES public.sizes (sizes_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.models
    OWNER to postgres;